services:
  server:
    image: golang:1.18-alpine
    volumes:
    - .:/src
    working_dir: /src
    command:
    - go
    - run
    - main.go
    - -c
    - /src/server.yaml
    - -w
    - --log.level
    - DEBUG
    ports:
    - 4195:4195/tcp
    - 4196:4196/tcp
    environment:
      INTROSPECT_URL: https://api.staging.numary.cloud/auth/introspect

  client:
    image: golang:1.18-alpine
    volumes:
    - .:/src
    working_dir: /src
    environment:
      ENDPOINT: http://server:4196
      ORGANIZATION: ${ORG}
      AUTH_URL: https://api.staging.numary.cloud/auth/authenticate/tokens
      AUTH_TOKEN: ${M2M_TOKEN}
    depends_on:
    - server
    command:
    - go
    - run
    - main.go
    - -c
    - /src/client.yaml
    - -w
    - --log.level
    - DEBUG
    ports:
    - 4194:4194/tcp
